routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEnd\HomeController@index');
Route::view('faq', 'frontend.faq');
Route::view('about', 'frontend.about');
Route::view('media', 'frontend.media');
Route::get('competition-one', 'FrontEnd\CompetitionOneController@index');
Route::get('competition-two', 'FrontEnd\CompetitionTwoController@index');

Route::get('login', 'RootController@index')->name('root')->middleware('guest');

Route::group([
    'as'            => 'students.',
    'prefix'        => 'students',
    'namespace'     => 'Students',
    'middleware'    => 'guest'
], function () {
    Route::get('register', 'RegisterController@showRegistrationForm')
        ->name('register');
    Route::post('register', 'RegisterController@register');

    Route::post('login', 'LoginController@login')->name('login');
});

Route::group([
    'as'            => 'students.',
    'prefix'        => 'students',
    'namespace'     => 'Students'
], function () {
    Route::get('email/verify/{id}', 'VerificationController@verify')
        ->middleware('signed', 'throttle:6,1')
        ->name('verification.verify');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'as'            => 'students.profile.',
    'prefix'        => 'students/profile',
    'namespace'     => 'Students',
    'middleware'    => 'auth:student'
], function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::get('edit', 'ProfileController@edit')->name('edit');
    Route::patch('', 'ProfileController@update')->name('update');
});

Route::group([
    'as'            => 'students.submission.',
    'prefix'        => 'students/submission',
    'namespace'     => 'Students',
    'middleware'    => 'auth:student'
], function () {
    Route::get('', 'SubmissionController@index')->name('index');
    Route::get('reviews', 'SubmissionController@reviews')->name('reviews');
    Route::get('success', 'SubmissionController@success')->name('success');
    Route::post('', 'SubmissionController@store')->name('store');
});

Route::group([
    'as'            => 'students.password.',
    'prefix'        => 'students/password',
    'namespace'     => 'Students'
], function () {
    Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')
        ->name('request');
    Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')
        ->name('email');
    Route::get('reset/{id}', 'ResetPasswordController@showResetForm')
        ->middleware('signed', 'throttle:6,1')
        ->name('reset');
    Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

Route::group([
    'as'            => 'juryMembers.',
    'prefix'        => 'jury-members',
    'namespace'     => 'JuryMembers',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::post('jury-members/logout', 'JuryMembers\LoginController@logout')
    ->name('juryMembers.logout');

Route::group([
    'as'            => 'juryMembers.',
    'prefix'        => 'jury-members',
    'namespace'     => 'JuryMembers',
    'middleware'    => 'auth:juryMember'
], function () {
    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');
    Route::get('review/{id}', 'ReviewController@create')
        ->name('review.create');
    Route::post('review/{id}', 'ReviewController@store');
});

Route::group([
    'as'            => 'admin.',
    'prefix'        => 'admin',
    'namespace'     => 'Admin',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::group([
    'as'            => 'admin.dashboard.',
    'prefix'        => 'admin/dashboard',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'DashboardController@index')->name('index');
    Route::delete('delete-entry/{id}', 'DashboardController@deleteEntry')
        ->name('deleteEntry');
});

Route::get('admin/entries/{id}/students', 'Admin\EntryController@students')
    ->name('admin.entries.students')->middleware('auth:admin');

Route::get('admin/reviews', 'Admin\ReviewController@index')
    ->name('admin.reviews.index')->middleware('auth:admin');

Route::group([
    'as'            => 'admin.juryMembers.',
    'prefix'        => 'admin/jury-members',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'JuryMemberController@index')->name('index');
    Route::post('', 'JuryMemberController@store')->name('store');
    Route::patch('{id}', 'JuryMemberController@update')->name('update');
    Route::delete('{id}', 'JuryMemberController@destroy')->name('destroy');
});

Route::group([
    'as'            => 'admin.competitionLock.',
    'prefix'        => 'admin/competition-lock',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'CompetitionLockController@index')->name('index');
    Route::get('results/{competition}', 'CompetitionLockController@results')
        ->name('results');
    Route::post('{competition}', 'CompetitionLockController@store')
        ->name('store');
});

Route::post('admin/logout', 'Admin\LoginController@logout')
    ->name('admin.logout');

resources/views/root.blade.php
@extends('layouts.app')

@section('title', 'Student Login')

@section('content')
    <div class="main-wrapper">
        <div class="inner-wrapper">
            <div class="top-part">
                @include('partials.head', [
                    'title' => 'SUBMISSION PORTAL',
                    'description' => 'In order to submit your work, you have to be a registered user.'
                ])

                <h2>ALREADY REGISTERED? LOGIN NOW</h2>

                <form action="{{ route('students.login') }}" method="POST">
                    @csrf

                    <div class="email-sec">
                        <div class="input-field">
                            <input type="text" name="username" value="{{ old('username') }}" id="Competitior_id"
                                class="validate" minlength="7" required>
                            <label for="Competitior_id">Competitior ID</label>

                            @error('username')
                                <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="contain-inputs">
                        <div class="input-cover left-section">
                            <div class="input-field">
                                <input type="email" name="email" value="{{ old('email') }}" id="email_feild" class="validate"
                                    autocomplete="email" required>
                                <label for="email_feild">Email</label>

                                @error('email')
                                    <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="input-field">
                                <input type="password" name="password" id="password" class="validate"
                                    autocomplete="current-password" minlength="8" required>
                                <label for="password">Password</label>

                                @error('password')
                                    <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="wrap-login-btn">
                            <button type="submit" class="waves-effect waves-light btn">Login</button>
                            <a href="{{ route('students.password.request') }}">Reset Password?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <section class="bottom-part">
        <h2>NEW HERE? GET REGISTERED NOW</h2>

        <div class="input-section">
            <span class="help-label">Select your entry type <img src="{{ asset('images/question.svg') }}" alt=""></span>

            <div class="inner-wrapper-bottom">
                <form action="{{ route('students.register') }}" method="GET">
                    <div class="register-form">
                        <div class="input-radio">
                            <label>
                                <input type="radio" name="type" value="individual">
                                <span>Individual Entry</span>
                            </label>
                        </div>

                        <div class="input-radio">
                            <label>
                                <input type="radio" name="type" value="group">
                                <span>Group Entry</span>
                            </label>
                        </div>

                        <button class="waves-effect waves-light btn">Proceed</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    @include('layouts.alerts')
@endsection