routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEnd\HomeController@index');
Route::view('faq', 'frontend.faq');
Route::view('about', 'frontend.about');
Route::view('media', 'frontend.media');
Route::get('competition-one', 'FrontEnd\CompetitionOneController@index');
Route::get('competition-two', 'FrontEnd\CompetitionTwoController@index');

Route::get('login', 'RootController@index')->name('root')->middleware('guest');

Route::group([
    'as'            => 'students.',
    'prefix'        => 'students',
    'namespace'     => 'Students',
    'middleware'    => 'guest'
], function () {
    Route::get('register', 'RegisterController@showRegistrationForm')
        ->name('register');
    Route::post('register', 'RegisterController@register');

    Route::post('login', 'LoginController@login')->name('login');
});

Route::group([
    'as'            => 'students.',
    'prefix'        => 'students',
    'namespace'     => 'Students'
], function () {
    Route::get('email/verify/{id}', 'VerificationController@verify')
        ->middleware('signed', 'throttle:6,1')
        ->name('verification.verify');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'as'            => 'students.profile.',
    'prefix'        => 'students/profile',
    'namespace'     => 'Students',
    'middleware'    => 'auth:student'
], function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::get('edit', 'ProfileController@edit')->name('edit');
    Route::patch('', 'ProfileController@update')->name('update');
});

Route::group([
    'as'            => 'students.submission.',
    'prefix'        => 'students/submission',
    'namespace'     => 'Students',
    'middleware'    => 'auth:student'
], function () {
    Route::get('', 'SubmissionController@index')->name('index');
    Route::get('reviews', 'SubmissionController@reviews')->name('reviews');
    Route::get('success', 'SubmissionController@success')->name('success');
    Route::post('', 'SubmissionController@store')->name('store');
});

Route::group([
    'as'            => 'students.password.',
    'prefix'        => 'students/password',
    'namespace'     => 'Students'
], function () {
    Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')
        ->name('request');
    Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')
        ->name('email');
    Route::get('reset/{id}', 'ResetPasswordController@showResetForm')
        ->middleware('signed', 'throttle:6,1')
        ->name('reset');
    Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

Route::group([
    'as'            => 'juryMembers.',
    'prefix'        => 'jury-members',
    'namespace'     => 'JuryMembers',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::post('jury-members/logout', 'JuryMembers\LoginController@logout')
    ->name('juryMembers.logout');

Route::group([
    'as'            => 'juryMembers.',
    'prefix'        => 'jury-members',
    'namespace'     => 'JuryMembers',
    'middleware'    => 'auth:juryMember'
], function () {
    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');
    Route::get('review/{id}', 'ReviewController@create')
        ->name('review.create');
    Route::post('review/{id}', 'ReviewController@store');
});

Route::group([
    'as'            => 'admin.',
    'prefix'        => 'admin',
    'namespace'     => 'Admin',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::group([
    'as'            => 'admin.dashboard.',
    'prefix'        => 'admin/dashboard',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'DashboardController@index')->name('index');
    Route::delete('delete-entry/{id}', 'DashboardController@deleteEntry')
        ->name('deleteEntry');
});

Route::get('admin/entries/{id}/students', 'Admin\EntryController@students')
    ->name('admin.entries.students')->middleware('auth:admin');

Route::get('admin/reviews', 'Admin\ReviewController@index')
    ->name('admin.reviews.index')->middleware('auth:admin');

Route::group([
    'as'            => 'admin.juryMembers.',
    'prefix'        => 'admin/jury-members',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'JuryMemberController@index')->name('index');
    Route::post('', 'JuryMemberController@store')->name('store');
    Route::patch('{id}', 'JuryMemberController@update')->name('update');
    Route::delete('{id}', 'JuryMemberController@destroy')->name('destroy');
});

Route::group([
    'as'            => 'admin.competitionLock.',
    'prefix'        => 'admin/competition-lock',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'CompetitionLockController@index')->name('index');
    Route::get('results/{competition}', 'CompetitionLockController@results')
        ->name('results');
    Route::post('{competition}', 'CompetitionLockController@store')
        ->name('store');
});

Route::post('admin/logout', 'Admin\LoginController@logout')
    ->name('admin.logout');

app/Http/Controllers/Students/ForgotPasswordController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Student;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Mail\PasswordResetRequested;

class ForgotPasswordController extends Controller
{
    /**
     * Display the form to request a password reset link.
     *
     * @return \Illuminate\View\View
     */
    public function showLinkRequestForm()
    {
        return view('students.auth.email');
    }

    /**
     * Send a reset link to the given user.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function sendResetLinkEmail()
    {
        $validated = request()->validate(['email' => 'required|email']);

        $student = Student::where(['email' => $validated['email']])->first(['id']);

        if (! $student) {
            return back()->with([
                'error' => "We can't find a student with that email address."
            ]);
        }

        Mail::to($validated['email'])->send(new PasswordResetRequested(
            $student
        ));

        return redirect()->route('root')->with([
            'success' => 'Password reset link sent. Please check your inbox.'
        ]);
    }
}

app/Http/Controllers/Students/LoginController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Entry;
use App\Models\Student;
use App\Http\Controllers\Controller;
use App\Http\Requests\Students\LogIn;

class LoginController extends Controller
{
    /**
     * Show the student's login form.
     *
     * @return \Illuminate\View\View
     */
    public function showLoginForm($id = null)
    {
        if (! $id) {
            return view('students.auth.login');
        }

        $student = Student::with(['entries:id,identity'])
            ->findOrFail($id, ['id']);

        return view('students.auth.login', compact('student'));
    }

    /**
     * Handle student login.
     *
     * @param  LogIn $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function login(LogIn $request)
    {
        $validated = $request->validated();

        $entry = Entry::where(['identity' => $validated['username']])->first();

        if (! $entry) {
            $error = 'No entry found by the id of ' . $validated['username'] . '.';

            return back()->withInput()->with(['error' => $error]);
        }

        if ($this->isAuthenticatable($validated)) {
            return $this->isEmailVerified($entry);
        }

        return back()->withInput()->with([
            'error' => 'Email/password is incorrect.'
        ]);
    }

    /**
     * Attempt to authenticate a student using given credentials.
     *
     * @param  array $validated
     * @return bool
     */
    public function isAuthenticatable(array $validated)
    {
        return auth()->guard('student')->attempt([
            'email'     => $validated['email'],
            'password'  => $validated['password']
        ]);
    }

    /**
     * Check whether the authenticated student has verified email.
     *
     * @param  Entry $entry
     * @return \Illuminate\Http\RedirectResponse
     */
    public function isEmailVerified($entry)
    {
        $student = auth()->guard('student')->user();

        if (! $student->email_verified_at) {
            $this->logout(false);

            return back()->withInput()
                ->with(['error' => 'Please verify your email.']);
        }

        session(['entry' => $entry]);

        return redirect()->route('students.profile.index');
    }

    /**
     * Log the student out of the application.
     *
     * @param  bool $return
     * @return \Illuminate\Http\RedirectResponse
     */
    public function logout($return = true)
    {
        auth()->guard('student')->logout();

        request()->session()->invalidate();

        request()->session()->regenerateToken();

        if ($return) {
            return redirect()->route('root');
        }
    }
}

app/Http/Controllers/Students/ProfileController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Student;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Students\UpdateProfile;

class ProfileController extends Controller
{
    /**
     * Show individual/group profile.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        if (! session()->has('entry')) {
            abort(404);
        }

        $entry = session('entry');

        $entry->load(['students']);

        return view('students.profile.index', compact('entry'));
    }

    /**
     * Edit individual/group profile.
     *
     * @return \Illuminate\View\View
     */
    public function edit()
    {
        if (! session()->has('entry')) {
            abort(404);
        }

        $entry = session('entry');

        $entry->load(['students']);

        return view('students.profile.edit', compact('entry'));
    }

    /**
     * Update individual/group profile.
     *
     * @return \Illuminate\View\View
     */
    public function update(UpdateProfile $request)
    {
        foreach($request->validated()['students'] as $id => $values) {
            if (! empty($values['avatar'])) {
                $values = $this->updateAvatar($id, $values);
            }

            Student::where(['id' => $id])->update($values);
        }

        return redirect()->route('students.profile.index')
            ->with(['success' => 'Profile updated.']);
    }

    /**
     * Update specified student's avatar.
     *
     * @param  int $id
     * @param  array $values
     * @return array
     */
    public function updateAvatar(int $id, array $values)
    {
        $student = Student::findOrFail($id, ['avatar']);

        Storage::delete([$student->avatar]);

        $values['avatar'] = $values['avatar']
            ->store('images/students', ['disk' => 'public']);

        return $values;
    }
}

app/Http/Controllers/Students/RegisterController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Entry;
use App\Models\Student;
use App\Http\Controllers\Controller;
use App\Http\Requests\Students\Register;

class RegisterController extends Controller
{
    /**
     * Show student's registration form.
     *
     * @return \Illuminate\View\View
     */
    public function showRegistrationForm()
    {
        if (request()->filled('type') && request('type') === 'individual') {
            return view('students.auth.individual');
        }

        if (request()->filled('type') && request('type') === 'group') {
            return view('students.auth.group');
        }

        abort(404);
    }

    /**
     * Handle student registration.
     *
     * @param  Register $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function register(Register $request)
    {
        $students = $this->verifyRegistered($request->validated()['students']);

        if ($students instanceof \Illuminate\Http\RedirectResponse) {
            return $students;
        }

        $entry = $this->createEntry();

        $this->createStudents($students, $entry->id);

        $message = "Registration successful. Your Competitor ID is {$entry->identity}. Please login.";

        return redirect()->route('root')->with(['success'   => $message]);
    }

    /**
     * Check whether the incoming entry can be attached to existing students.
     *
     * @param  array $students
     * @return array|\Illuminate\Http\RedirectResponse
     */
    public function verifyRegistered(array $students)
    {
        $existingStudents = [];

        foreach ($students as $key => $student) {
            $existingStudent = $this->getExistingStudent($student);

            if (!$existingStudent) {
                continue;
            }

            if ($existingStudent->entries->count() === 2) {
                $error = $student['name'] . ' already has 2 entries.';

                return back()->withInput()->with(['error' => $error]);
            }

            if ($existingStudent->entries->count() === 1) {
                $validity = $this->isValidEntry($existingStudent);

                if (! $validity['status']) {
                    return back()->withInput()
                        ->with(['error' => $validity['error']]);
                }

                unset($students[$key]);

                array_push($existingStudents, $existingStudent);
            } else {
                return back()->withInput()
                    ->with('error', 'Please contact system administrator.');
            }
        }

        return [
            'submittedStudents' => $students,
            'existingStudents'  => $existingStudents
        ];
    }

    /**
     * Get existing student using incoming request values.
     *
     * @param  array $student
     * @return Student
     */
    public function getExistingStudent(array $student)
    {
        return Student::withTrashed()->select(['id', 'name'])
            ->with(['entries:id,type'])
            ->where(['nic' => $student['nic']])
            ->orWhere(['email' => $student['email']])
            ->first();
    }

    /**
     *  Check if the specified student can create an entry of incoming type.
     *
     * @param  Student $student
     * @return array
     */
    public function isValidEntry(Student $student)
    {
        $incomingStudents = count(request('students'));

        $existingEntry = $student->entries->first()->type;

        if ($incomingStudents === 1 && $existingEntry === 'individual') {
            return [
                'status'=> false,
                'error' => $student->name . ' already has an individual entry.'
            ];
        }

        if ($incomingStudents === 3 && $existingEntry === 'group') {
            return [
                'status'=> false,
                'error' => $student->name . ' already has a group entry.'
            ];
        }

        return ['status'=> true];
    }

    /**
     * Create an entry.
     *
     * @return Entry $entry
     */
    public function createEntry()
    {
        $type = count(request('students')) > 1 ? 'group' : 'individual';

        $entry = Entry::create(['identity' => 'PCCSDC', 'type' => $type]);

        $entry->identity .= $entry->id;

        $entry->save();

        return $entry;
    }

    /**
     * Create students.
     *
     * @param  array $students
     * @param  int $entryId
     * @return void
     */
    public function createStudents(array $students, int $entryId)
    {
        $this->setEntryToRegistered($students, $entryId);

        if (! empty($students['submittedStudents'])) {
            foreach ($students['submittedStudents'] as $student) {
                $student['password'] = request('students.0.password');
                $student['email_verified_at'] = now();

                $student = Student::create($student);

                $student->entries()->attach($entryId);
            }
        }
    }

    /**
     * Attach newly created entry to existing students.
     *
     * @param  array $students
     * @param  int $entryId
     * @return void
     */
    public function setEntryToRegistered(array $students, int $entryId)
    {
        if (! empty($students['existingStudents'])) {
            foreach ($students['existingStudents'] as $student) {
                $student->entries()->attach($entryId);
            }
        }
    }
}

app/Http/Controllers/Students/VerificationController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Student;
use App\Http\Controllers\Controller;

class VerificationController extends Controller
{
    /**
     * Mark the specified user's email address as verified.
     *
     * @param  int  $id
     */
    public function verify($id)
    {
        $student = Student::with(['entries:id,identity'])->findOrFail($id, ['id', 'email']);

        $student->email_verified_at = now();

        $student->save();

        return view('students.auth.login', compact('student'));
    }
}

resources/views/students/profile/details.blade.php
@php
    $avatar = ! empty($student->avatar) ? Storage::url($student->avatar)
        : asset('images/profile-image01.png');
@endphp

@if ($edit)
    <form action="{{ route('students.profile.update') }}" method="POST" enctype="multipart/form-data">
@endif

    @csrf
    @method('PATCH')

    <div class="profile-component">
        <div class="profile-card">
            <div class="wrap-back">
                <img src="{{ $avatar }}" alt="{{ $student->name }}'s Profile Picture">

                @if ($edit)
                    <div class="cam-upload">
                        <input type="file" name="students[{{ $student->id }}][avatar]" accept="image/*">
                    </div>
                @endif
            </div>

            <div class="profile-title-section">
                <h5>{{ $student->name }}</h5>
                <h5>{{ $entry->identity }}</h5>
            </div>
        </div>

        <div class="wrap-input-ele profile-spaceing">
            <div class="lft-sec">
                <div class="profile-iteam">
                    <p class="profile-title">NIC</p>
                    <p class="profile-head">{{ $student->nic }}</p>
                </div>

                <div class="profile-iteam">
                    <p class="profile-title">Email Address</p>
                    <p class="profile-head">{{ $student->email }}</p>
                </div>

                <div class="profile-iteam">
                    @if ($edit)
                        <div class="input-field">
                            <input type="tel" name="students[{{ $student->id }}][contact]"
                                value="{{ $student->contact }}" id="contactNo{{ $loop->iteration }}" class="validate"
                                minlength="12" placeholder="+947xzzzzzzz" autocomplete="mobile">
                            <label for="contactNo{{ $loop->iteration }}">Contact Number</label>

                            @error("students.$student->id.contact")
                                <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                            @enderror
                        </div>
                    @else
                        <p class="profile-title">Contact Number</p>
                        <p class="profile-head">{{ $student->contact }}</p>
                    @endif
                </div>
            </div>

            <div class="lft-sec">
                <div class="profile-iteam">
                    <p class="profile-title">University</p>
                    <p class="profile-head">{{ $student->university }}</p>
                </div>

                <div class="profile-iteam">
                    @if ($edit)
                        <div class="input-field">
                            <input type="text" name="students[{{ $student->id }}][registration]"
                                value="{{ $student->registration }}" id="registration{{ $loop->iteration }}"
                                class="validate">
                            <label for="registration{{ $loop->iteration }}">University Student Number</label>

                            @error("students.$student->id.contact")
                                <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                            @enderror
                        </div>
                    @else
                        <p class="profile-title">University Student Number</p>
                        <p class="profile-head">{{ $student->registration }}</p>
                    @endif
                </div>

                <div class="profile-iteam">
                    <div class="profile-iteam">
                        @if ($edit)
                            <div class="input-field">
                                <input type="text" name="students[{{ $student->id }}][course]"
                                    value="{{ $student->course }}" id="course{{ $loop->iteration }}" class="validate">
                                <label for="course{{ $loop->iteration }}">Course Following</label>

                                @error("students.$student->id.course")
                                    <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                                @enderror
                            </div>
                        @else
                            <p class="profile-title">Course Following</p>
                            <p class="profile-head">{{ $student->course }}</p>
                        @endif
                    </div>
                </div>
            </div>

            <div class="lft-sec">
                <div class="profile-iteam">
                    @if ($edit)
                        <div class="input-field">
                            <input type="number" name="students[{{ $student->id }}][year]" value="{{ $student->year }}"
                                id="yearOfStudy{{ $loop->iteration }}" class="validate" min="1" step="1">
                            <label for="yearOfStudy{{ $loop->iteration }}">Year of Study</label>

                            @error("students.$student->id.year")
                                <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                            @enderror
                        </div>
                    @else
                        <p class="profile-title">Year of Study</p>
                        <p class="profile-head">{{ $student->year }}</p>
                    @endif
                </div>

                <div class="profile-iteam">
                    @if ($edit)
                        <button type="submit" class="waves-effect waves-light btn">Save</button>
                    @else
                        <a href="{{ route('students.profile.edit') }}" class="waves-effect waves-light btn">
                            Edit Profile
                        </a>
                    @endif
                </div>
            </div>
        </div>
    </div>

@if ($edit)
    </form>
@endif

resources/views/students/profile/edit.blade.php
@extends('layouts.app')

@section('title', 'Student Profile')

@section('content')
    <div class="main-wrapper">
        @include('students.auth.logout', ['entry' => $entry])

        <div class="full-contact-container-second">
            @include('partials.head', ['title' => 'PROFILE'])

            @foreach ($entry->students as $student)
                @include('students.profile.details', ['entry' => $entry, 'student' => $student, 'edit' => true])
            @endforeach
        </div>
    </div>

    @include('layouts.alerts')
@endsection

resources/views/students/profile/index.blade.php
@extends('layouts.app')

@section('title', 'Student Profile')

@section('content')
    <div class="main-wrapper">
        @include('students.auth.logout', ['entry' => $entry])

        <div class="full-contact-container-second">
            @include('partials.head', ['title' => 'PROFILE'])

            @foreach ($entry->students as $student)
                @include('students.profile.details', ['entry' => $entry, 'student' => $student, 'edit' => false])
            @endforeach
        </div>
    </div>

    @include('layouts.alerts')
@endsection