routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEnd\HomeController@index');
Route::view('faq', 'frontend.faq');
Route::view('about', 'frontend.about');
Route::view('media', 'frontend.media');
Route::get('competition-one', 'FrontEnd\CompetitionOneController@index');
Route::get('competition-two', 'FrontEnd\CompetitionTwoController@index');

Route::get('login', 'RootController@index')->name('root')->middleware('guest');

Route::group([
    'as'            => 'students.',
    'prefix'        => 'students',
    'namespace'     => 'Students',
    'middleware'    => 'guest'
], function () {
    Route::get('register', 'RegisterController@showRegistrationForm')
        ->name('register');
    Route::post('register', 'RegisterController@register');

    Route::post('login', 'LoginController@login')->name('login');
});

Route::group([
    'as'            => 'students.',
    'prefix'        => 'students',
    'namespace'     => 'Students'
], function () {
    Route::get('email/verify/{id}', 'VerificationController@verify')
        ->middleware('signed', 'throttle:6,1')
        ->name('verification.verify');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'as'            => 'students.profile.',
    'prefix'        => 'students/profile',
    'namespace'     => 'Students',
    'middleware'    => 'auth:student'
], function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::get('edit', 'ProfileController@edit')->name('edit');
    Route::patch('', 'ProfileController@update')->name('update');
});

Route::group([
    'as'            => 'students.submission.',
    'prefix'        => 'students/submission',
    'namespace'     => 'Students',
    'middleware'    => 'auth:student'
], function () {
    Route::get('', 'SubmissionController@index')->name('index');
    Route::get('reviews', 'SubmissionController@reviews')->name('reviews');
    Route::get('success', 'SubmissionController@success')->name('success');
    Route::post('', 'SubmissionController@store')->name('store');
});

Route::group([
    'as'            => 'students.password.',
    'prefix'        => 'students/password',
    'namespace'     => 'Students'
], function () {
    Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')
        ->name('request');
    Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')
        ->name('email');
    Route::get('reset/{id}', 'ResetPasswordController@showResetForm')
        ->middleware('signed', 'throttle:6,1')
        ->name('reset');
    Route::post('reset', 'ResetPasswordController@reset')->name('update');
});

Route::group([
    'as'            => 'juryMembers.',
    'prefix'        => 'jury-members',
    'namespace'     => 'JuryMembers',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::post('jury-members/logout', 'JuryMembers\LoginController@logout')
    ->name('juryMembers.logout');

Route::group([
    'as'            => 'juryMembers.',
    'prefix'        => 'jury-members',
    'namespace'     => 'JuryMembers',
    'middleware'    => 'auth:juryMember'
], function () {
    Route::get('dashboard', 'DashboardController@index')
        ->name('dashboard.index');
    Route::get('review/{id}', 'ReviewController@create')
        ->name('review.create');
    Route::post('review/{id}', 'ReviewController@store');
});

Route::group([
    'as'            => 'admin.',
    'prefix'        => 'admin',
    'namespace'     => 'Admin',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::group([
    'as'            => 'admin.dashboard.',
    'prefix'        => 'admin/dashboard',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'DashboardController@index')->name('index');
    Route::delete('delete-entry/{id}', 'DashboardController@deleteEntry')
        ->name('deleteEntry');
});

Route::get('admin/entries/{id}/students', 'Admin\EntryController@students')
    ->name('admin.entries.students')->middleware('auth:admin');

Route::get('admin/reviews', 'Admin\ReviewController@index')
    ->name('admin.reviews.index')->middleware('auth:admin');

Route::group([
    'as'            => 'admin.juryMembers.',
    'prefix'        => 'admin/jury-members',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'JuryMemberController@index')->name('index');
    Route::post('', 'JuryMemberController@store')->name('store');
    Route::patch('{id}', 'JuryMemberController@update')->name('update');
    Route::delete('{id}', 'JuryMemberController@destroy')->name('destroy');
});

Route::group([
    'as'            => 'admin.competitionLock.',
    'prefix'        => 'admin/competition-lock',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'CompetitionLockController@index')->name('index');
    Route::get('results/{competition}', 'CompetitionLockController@results')
        ->name('results');
    Route::post('{competition}', 'CompetitionLockController@store')
        ->name('store');
});

Route::post('admin/logout', 'Admin\LoginController@logout')
    ->name('admin.logout');

app/Http/Controllers/Students/ForgotPasswordController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Student;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Mail\PasswordResetRequested;

class ForgotPasswordController extends Controller
{
    /**
     * Display the form to request a password reset link.
     *
     * @return \Illuminate\View\View
     */
    public function showLinkRequestForm()
    {
        return view('students.auth.email');
    }

    /**
     * Send a reset link to the given user.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function sendResetLinkEmail()
    {
        $validated = request()->validate(['email' => 'required|email']);

        $student = Student::where(['email' => $validated['email']])->first(['id']);

        if (! $student) {
            return back()->with([
                'error' => "We can't find a student with that email address."
            ]);
        }

        Mail::to($validated['email'])->send(new PasswordResetRequested(
            $student
        ));

        return redirect()->route('root')->with([
            'success' => 'Password reset link sent. Please check your inbox.'
        ]);
    }
}

app/Http/Controllers/Students/LoginController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Entry;
use App\Models\Student;
use App\Http\Controllers\Controller;
use App\Http\Requests\Students\LogIn;

class LoginController extends Controller
{
    /**
     * Show the student's login form.
     *
     * @return \Illuminate\View\View
     */
    public function showLoginForm($id = null)
    {
        if (! $id) {
            return view('students.auth.login');
        }

        $student = Student::with(['entries:id,identity'])
            ->findOrFail($id, ['id']);

        return view('students.auth.login', compact('student'));
    }

    /**
     * Handle student login.
     *
     * @param  LogIn $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function login(LogIn $request)
    {
        $validated = $request->validated();

        $entry = Entry::where(['identity' => $validated['username']])->first();

        if (! $entry) {
            $error = 'No entry found by the id of ' . $validated['username'] . '.';

            return back()->withInput()->with(['error' => $error]);
        }

        if ($this->isAuthenticatable($validated)) {
            return $this->isEmailVerified($entry);
        }

        return back()->withInput()->with([
            'error' => 'Email/password is incorrect.'
        ]);
    }

    /**
     * Attempt to authenticate a student using given credentials.
     *
     * @param  array $validated
     * @return bool
     */
    public function isAuthenticatable(array $validated)
    {
        return auth()->guard('student')->attempt([
            'email'     => $validated['email'],
            'password'  => $validated['password']
        ]);
    }

    /**
     * Check whether the authenticated student has verified email.
     *
     * @param  Entry $entry
     * @return \Illuminate\Http\RedirectResponse
     */
    public function isEmailVerified($entry)
    {
        $student = auth()->guard('student')->user();

        if (! $student->email_verified_at) {
            $this->logout(false);

            return back()->withInput()
                ->with(['error' => 'Please verify your email.']);
        }

        session(['entry' => $entry]);

        return redirect()->route('students.profile.index');
    }

    /**
     * Log the student out of the application.
     *
     * @param  bool $return
     * @return \Illuminate\Http\RedirectResponse
     */
    public function logout($return = true)
    {
        auth()->guard('student')->logout();

        request()->session()->invalidate();

        request()->session()->regenerateToken();

        if ($return) {
            return redirect()->route('root');
        }
    }
}

app/Http/Controllers/Students/ProfileController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Student;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Students\UpdateProfile;

class ProfileController extends Controller
{
    /**
     * Show individual/group profile.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        if (! session()->has('entry')) {
            abort(404);
        }

        $entry = session('entry');

        $entry->load(['students']);

        return view('students.profile.index', compact('entry'));
    }

    /**
     * Edit individual/group profile.
     *
     * @return \Illuminate\View\View
     */
    public function edit()
    {
        if (! session()->has('entry')) {
            abort(404);
        }

        $entry = session('entry');

        $entry->load(['students']);

        return view('students.profile.edit', compact('entry'));
    }

    /**
     * Update individual/group profile.
     *
     * @return \Illuminate\View\View
     */
    public function update(UpdateProfile $request)
    {
        foreach($request->validated()['students'] as $id => $values) {
            if (! empty($values['avatar'])) {
                $values = $this->updateAvatar($id, $values);
            }

            Student::where(['id' => $id])->update($values);
        }

        return redirect()->route('students.profile.index')
            ->with(['success' => 'Profile updated.']);
    }

    /**
     * Update specified student's avatar.
     *
     * @param  int $id
     * @param  array $values
     * @return array
     */
    public function updateAvatar(int $id, array $values)
    {
        $student = Student::findOrFail($id, ['avatar']);

        Storage::delete([$student->avatar]);

        $values['avatar'] = $values['avatar']
            ->store('images/students', ['disk' => 'public']);

        return $values;
    }
}

app/Http/Controllers/Students/RegisterController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Entry;
use App\Models\Student;
use App\Http\Controllers\Controller;
use App\Http\Requests\Students\Register;

class RegisterController extends Controller
{
    /**
     * Show student's registration form.
     *
     * @return \Illuminate\View\View
     */
    public function showRegistrationForm()
    {
        if (request()->filled('type') && request('type') === 'individual') {
            return view('students.auth.individual');
        }

        if (request()->filled('type') && request('type') === 'group') {
            return view('students.auth.group');
        }

        abort(404);
    }

    /**
     * Handle student registration.
     *
     * @param  Register $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function register(Register $request)
    {
        $students = $this->verifyRegistered($request->validated()['students']);

        if ($students instanceof \Illuminate\Http\RedirectResponse) {
            return $students;
        }

        $entry = $this->createEntry();

        $this->createStudents($students, $entry->id);

        $message = "Registration successful. Your Competitor ID is {$entry->identity}. Please login.";

        return redirect()->route('root')->with(['success'   => $message]);
    }

    /**
     * Check whether the incoming entry can be attached to existing students.
     *
     * @param  array $students
     * @return array|\Illuminate\Http\RedirectResponse
     */
    public function verifyRegistered(array $students)
    {
        $existingStudents = [];

        foreach ($students as $key => $student) {
            $existingStudent = $this->getExistingStudent($student);

            if (!$existingStudent) {
                continue;
            }

            if ($existingStudent->entries->count() === 2) {
                $error = $student['name'] . ' already has 2 entries.';

                return back()->withInput()->with(['error' => $error]);
            }

            if ($existingStudent->entries->count() === 1) {
                $validity = $this->isValidEntry($existingStudent);

                if (! $validity['status']) {
                    return back()->withInput()
                        ->with(['error' => $validity['error']]);
                }

                unset($students[$key]);

                array_push($existingStudents, $existingStudent);
            } else {
                return back()->withInput()
                    ->with('error', 'Please contact system administrator.');
            }
        }

        return [
            'submittedStudents' => $students,
            'existingStudents'  => $existingStudents
        ];
    }

    /**
     * Get existing student using incoming request values.
     *
     * @param  array $student
     * @return Student
     */
    public function getExistingStudent(array $student)
    {
        return Student::withTrashed()->select(['id', 'name'])
            ->with(['entries:id,type'])
            ->where(['nic' => $student['nic']])
            ->orWhere(['email' => $student['email']])
            ->first();
    }

    /**
     *  Check if the specified student can create an entry of incoming type.
     *
     * @param  Student $student
     * @return array
     */
    public function isValidEntry(Student $student)
    {
        $incomingStudents = count(request('students'));

        $existingEntry = $student->entries->first()->type;

        if ($incomingStudents === 1 && $existingEntry === 'individual') {
            return [
                'status'=> false,
                'error' => $student->name . ' already has an individual entry.'
            ];
        }

        if ($incomingStudents === 3 && $existingEntry === 'group') {
            return [
                'status'=> false,
                'error' => $student->name . ' already has a group entry.'
            ];
        }

        return ['status'=> true];
    }

    /**
     * Create an entry.
     *
     * @return Entry $entry
     */
    public function createEntry()
    {
        $type = count(request('students')) > 1 ? 'group' : 'individual';

        $entry = Entry::create(['identity' => 'PCCSDC', 'type' => $type]);

        $entry->identity .= $entry->id;

        $entry->save();

        return $entry;
    }

    /**
     * Create students.
     *
     * @param  array $students
     * @param  int $entryId
     * @return void
     */
    public function createStudents(array $students, int $entryId)
    {
        $this->setEntryToRegistered($students, $entryId);

        if (! empty($students['submittedStudents'])) {
            foreach ($students['submittedStudents'] as $student) {
                $student['password'] = request('students.0.password');
                $student['email_verified_at'] = now();

                $student = Student::create($student);

                $student->entries()->attach($entryId);
            }
        }
    }

    /**
     * Attach newly created entry to existing students.
     *
     * @param  array $students
     * @param  int $entryId
     * @return void
     */
    public function setEntryToRegistered(array $students, int $entryId)
    {
        if (! empty($students['existingStudents'])) {
            foreach ($students['existingStudents'] as $student) {
                $student->entries()->attach($entryId);
            }
        }
    }
}

app/Http/Controllers/Students/VerificationController.php
<?php

namespace App\Http\Controllers\Students;

use App\Models\Student;
use App\Http\Controllers\Controller;

class VerificationController extends Controller
{
    /**
     * Mark the specified user's email address as verified.
     *
     * @param  int  $id
     */
    public function verify($id)
    {
        $student = Student::with(['entries:id,identity'])->findOrFail($id, ['id', 'email']);

        $student->email_verified_at = now();

        $student->save();

        return view('students.auth.login', compact('student'));
    }
}

resources/views/students/submission/index.blade.php
@extends('layouts.app')

@section('title', 'Student Submission')

@section('content')
<div class="main-wrapper">
    @include('students.auth.logout', ['entry' => session('entry')])

    <div class="full-contact-container">
        <div class="spacer">
            @include('partials.head', ['title' => 'COMPETITION'])
        </div>

        <div class="containre-sec">
            <ul class="progressbar">
                <li class="active">
                    <img src="{{ asset('images/tick.png') }}" alt="">
                    Submission
                </li>
                <li>Result</li>
            </ul>
        </div>

        <form action="{{ route('students.submission.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="select-competition">
                <span class="title-label">Select competition</span>

                <label>
                    <input type="radio" name="competition" value="1" class="validate" required>
                    <span>Interactive Wall - Submissions Closed</span>
                </label>

                <label>
                    <input type="radio" name="competition" value="2" class="validate" required disabled>
                    <span>Beach Sculpture - Submissions Closed</span>
                </label>
            </div>

            @error('competition')
            <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
            @enderror

            <div class="upload-document">
                <span class="title-label">Select competition</span>

                <div class="documents">
                    <div class="doc-one">
                        <p class="box-title">Proposal</p>
                        <p class="format">Format: <span>PDF</span></p>
                        <p class="m-size">Max Size: <span>20MB</span></p>

                        <div class="file-field input-field">
                            <div class="btn">
                                <span>UPLOAD</span>
                                <input type="file" name="proposal" accept=".pdf" class="validate" required>
                            </div>

                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>

                        @error('proposal')
                        <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="doc-two">
                        <p class="box-title">Design</p>
                        <p class="format">Format: <span>PDF</span></p>
                        <p class="m-size">Max Size: <span>20MB</span></p>

                        <div class="file-field input-field">
                            <div class="btn">
                                <span>UPLOAD</span>
                                <input type="file" name="design" accept=".pdf" class="validate" required>
                            </div>

                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>

                        @error('design')
                        <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
            </div>

            <p class="agreement">
                <label>
                    <input type="checkbox" name="terms" class="validate" required>
                    <span>I/we have read and understood all the rules & guidelines stipulated under ‘rules &
                        guidelines’ of the competition and agree to the same; and I/We confirm that the design
                        submitted by me/ us is an original work, and it is not copied or reproduced.</span>
                </label>

                {{-- <a href="#modal1" class="modal-trigger tearm">Tearms & Conditions</a> --}}
            </p>

            @error('terms')
            <span class="helper-text" data-error="{{ $message }}">{{ $message }}</span>
            @enderror

            {{-- <div id="modal1" class="modal">
                    <div class="modal-content">
                        <a href="#!" class="close-btn">
                            <img class="modal-close" src="{{ asset('images/close.svg') }}" alt="">
            </a>

            <h4>Terms & Conditions</h4>

            <p>I/we have read and understood all the rules & guidelines stipulated under ‘rules &
                guidelines’ of the competition and agree to the same; and I/We confirm that the design
                submitted by me/ us is an original work, and it is not copied or reproduced.</p>
    </div>
</div> --}}

<div class="submit-button">
    <button data-target="modal12" class="waves-effect waves-light btn modal-trigger">Submit</button>
</div>

<div id="modal12" class="modal">
    <div class="modal-content">
        <h4>Confirmation</h4>

        <p>Hope you have uploaded the required 2 documents against the correct compition.</p>

        <p>By clicking ‘YES’ will complet the sumission and you will not be able to do any amendments
            here after.</p>

        <p>By clicking ‘NO’ you can go back and check on the selections that you have done.</p>
    </div>

    <div class="con-btns">
        <button type="submit" class="waves-effect waves-light btn ">YES</button>
        <button type="button" class="waves-effect waves-light btn btn-outline"
            onclick="$('#modal12').modal('close')">NO</button>
    </div>
</div>
</form>
</div>
</div>

@include('layouts.alerts')
@endsection

@push('scripts')
<script>
    $('.modal').modal();
        $('.modal-confirm').modal();
</script>
@endpush

resources/views/students/submission/reviews.blade.php
@extends('layouts.app')

@section('title', 'Reviews')

@section('content')
    <div class="main-wrapper">
        @include('students.auth.logout', ['entry' => session('entry')])

        <div class="full-contact-container">
            <div class="spacer">
                @include('partials.head', ['title' => 'COMPETITION'])
            </div>

            <div class="containre-sec">
                <ul class="progressbar">
                    <li class="active">
                        <img src="{{ asset('images/tick.png') }}" alt="">
                        Submission
                    </li>

                    <li class="active">
                        <img src="{{ asset('images/tick.png') }}" alt="">
                        Result
                    </li>
                </ul>
            </div>

            @if ($entry->submissions->isNotEmpty())
                @foreach ($entry->submissions as $submission)
                    <table class="striped highlight responsive-table">
                        <thead>
                            <tr>
                                <th>Points</th>
                                <th>Comments</th>
                            </tr>
                        </thead>

                        <tbody>
                            @if ($submission->reviews->isNotEmpty())
                                @foreach ($submission->reviews as $review)
                                    <tr>
                                        <td>{{ $review->points }}</td>
                                        <td>{{ $review->comments }}</td>
                                    </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                @endforeach
            @endif
        </div>
    </div>
@endsection

resources/views/students/submission/success.blade.php
@extends('layouts.app')

@section('title', 'Student Submission')

@section('content')
    <div class="main-wrapper">
        @include('students.auth.logout', ['entry' => session('entry')])

        <div class="full-contact-container">
            <div class="spacer">
                @include('partials.head', ['title' => 'COMPETITION'])
            </div>

            <div class="containre-sec">
                <ul class="progressbar">
                    <li class="active">
                        <img src="{{ asset('images/tick.png') }}" alt="">
                        Submission
                    </li>
                    <li>Result</li>
                </ul>
            </div>

            <h2>Congrats! You have successfully submitted your design.</h2>

            <h5>The Jury will carefully go through your proposel and the design soon.</h5>

            <h5>Get in touch with us, we will update you soon on the results.</h5>
        </div>
    </div>

    @include('layouts.alerts')
@endsection